=== Opetushallitus/tarjonta/tarjonta-api/src/main/resources/wsdl/learningUploadService.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://service.tarjonta.sade.vm.fi/types" version="1.0"
           xmlns:xml="http://www.w3.org/XML/1998/namespace"
           xmlns:tns="http://service.tarjonta.sade.vm.fi/types"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
               schemaLocation="http://www.w3.org/2001/03/xml.xsd">
        <xs:annotation>
            <xs:documentation xml:lang="fi">
                XML-nimiavaruus xml:lang -attribuutin vuoksi.
            </xs:documentation>
        </xs:annotation>
    </xs:import>


    <xs:element name="LearningUploadRequest" type="tns:LearningUploadRequestType" />
    <xs:element name="LearningUploadResponse" type="tns:LearningUploadResponseType" />
    <xs:element name="LearningOpportunityData" type="tns:LearningOpportunityDataType" />

    <xs:complexType name="LearningUploadResponseType">
    </xs:complexType>

    <xs:complexType name="LearningUploadRequestType">
        <xs:sequence>
            <xs:element name="LearningOpportunityData"
                        type="tns:LearningOpportunityDataType"
                        minOccurs="0"
                        maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="LearningOpportunityDataType">
        <xs:sequence>
            <xs:element name="LearningOpportunitySpecification"
                        type="tns:LearningOpportunitySpecificationType"
                        minOccurs="0"
                        maxOccurs="unbounded"/>
            <xs:element name="LearningOpportunityProvider"
                        type="tns:LearningOpportunityProviderType"
                        minOccurs="0"
                        maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LearningOpportunityObjectType" abstract="true">
        <xs:sequence>
            <xs:element name="Name"
                        type="tns:TextType"
                        minOccurs="0"
                        maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:attributeGroup name="LearningOpportunityModuleAttrGroup">
        <xs:annotation>
            <xs:documentation xml:lang="fi">
                Yleisia LearningOpportunity:lle sekä LearningOpportunitySpecification:lle yhteisia attribuutteja.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="type" type="tns:LearningOpportunityType" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="LearningOpportunitySpecificationType">
        <xs:complexContent>
            <xs:extension base="tns:LearningOpportunityObjectType">
                <xs:sequence>
                    <xs:element name="OfferedBy"
                                type="tns:LearningOpportunityProviderRefType"
                                minOccurs="0"
                                maxOccurs="1"/>
                    <xs:element name="Credits"
                                type="tns:CreditsType"
                                minOccurs="0"
                                maxOccurs="1"/>
                    <xs:element name="Structure"
                                type="tns:StructureType"
                                minOccurs="0"
                                maxOccurs="1"/>
                </xs:sequence>
                <xs:attribute name="id"
                              type="xs:ID"
                              use="optional"/>
                <xs:attributeGroup ref="tns:LearningOpportunityModuleAttrGroup"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="StructureType">
        <xs:sequence>
            <xs:element name="SpecificationRef"
                        type="tns:LearningOpportunitySpecificationRefType"
                        minOccurs="1"
                        maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="selector" type="tns:StructureSelectorType"/>
    </xs:complexType>

    <xs:complexType name="LearningOpportunitySpecificationRefType">
        <xs:attribute name="ref"
                      type="xs:IDREF"
                      use="required"/>
    </xs:complexType>

    <xs:complexType name="LearningOpportunityProviderRefType">
        <xs:attribute name="ref"
                      type="xs:IDREF"
                      use="required"/>
    </xs:complexType>

    <xs:complexType name="LearningOpportunityProviderType">
        <xs:sequence>
            <xs:element name="InstitutionName"
                        type="tns:ExtendedStringType"
                        minOccurs="0"
                        maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Organisaation nimi / koulutustoimijan nimi.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="InstitutionAcademicCalendar"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        lukukausien ja periodien sekä opetustarjonnan ajankohdat kertova koulutustoimijan kalenteri
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="InstitutionAcademicAuthorities"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Opetuksen vastuuhenkilöt.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="InstitutionAdmissionProcedures"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa opeskelijavalintojen toteutuksesta.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="InstitutionGeneralDescription"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Organisaation yleiskuvaus.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="InstitutionalEctsCoordinator"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Organisaation ECTS-koordinaattori.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="InstitutionMainUniversityRequlations"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Opetusten tunnustamissäännöt organisaatiossa.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnCostOfLiving"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa elämisen kustannuksista.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnMeals"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa opiskelijaruokalusta.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnMedicalFacilities"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa terveydenhuoltopalveluista.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnFacilitiesForStudentsWithSpecialNeeds"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Esteettömyys ja vammaisten tukipalvelut.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnInsurance"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa vakuutuksista.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnFinancialSupport"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa opintojen rahoituksesta.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnStudentAffairsOffice"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa opintotoimistosta ja opiskelijapalveluista.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnStudyFacilities"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa oppimisympäristöstä.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnInternationalProgrammes"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa kansainvälisistä koulutusohjelmista, vieraskielisistä koulutusohjelmista.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationForMobileStudents"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa opiskelijaliikkuvuudesta.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnLanguageCourses"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa kieliopinnoista.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnInternships"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa opintoihin liittyvistä työharjoitteluista.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnSportsFacilities"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa opiskelijaliikunnasta.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnExtraMuralAndLeisureFacilities"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa vapaa-ajan palveluista.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="GeneralInformationOnStudentAssociations"
                        type="xs:string"
                        minOccurs="0"
                        maxOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tietoa opiskelijajärjestöistä.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>

        <xs:attribute name="id"
                      type="xs:ID"
                      use="optional">
            <xs:annotation>
                <xs:documentation xml:lang="fi">doc for id</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>


    <xs:simpleType name="StructureSelectorType">
        <xs:restriction base="xs:normalizedString">
            <xs:enumeration value="oneOf">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Osista valitaan yksi.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="allOf">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Kaikki osat kuuluvat mukaan koosteeseen.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="numberOf">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Osista valitaan maaritelty lukumaara (min, max) koosteeseen.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="someOf">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Rakenneyksikko koostetaan epamaaraisella saannolla. Saanto kuvataan
                        annotation-elementissa.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="ects">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Koosteeseen otetaan mukaan tietty maara opintopisteita (min. max) osista yhteenlaskettuna.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="cu">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Koosteeseen otetaan mukaan tietty maara opintoviikkoja (min. max) osista yhteenlaskettuna.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="LearningOpportunityType">
        <xs:restriction base="xs:normalizedString">
            <xs:enumeration value="DegreeProgramme">
                <xs:annotation>
                    <xs:documentation xml:lang="fi">
                        Tutkintoon johtava ohjelma
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="TextType" mixed="true">
        <xs:attribute ref="xml:lang"/>
    </xs:complexType>

    <xs:complexType name="ExtendedStringType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- -->
    <xs:complexType name="CreditsType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="unit" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <!-- credit units -->
                            <xs:enumeration value="cu"/>
                            <!-- ECTS credit -->
                            <xs:enumeration value="ects"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


</xs:schema>

=== Opetushallitus/tarjonta/tarjonta-api/src/test/resources/learningUploadSample.xml
<?xml version="1.0" encoding="UTF-8"?>

<LearningOpportunityData
    xmlns="http://service.tarjonta.sade.vm.fi/types"
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:schemaLocation='http://service.tarjonta.sade.vm.fi/types  ../../main/resources/wsdl/learningUploadService.xsd'>


    <LearningOpportunitySpecification id="LOS1">
        <OfferedBy ref="LOP1"/>
        <Structure selector="allOf">
            <SpecificationRef ref="LOS2"/>
            <SpecificationRef ref="LOS3"/>
        </Structure>
    </LearningOpportunitySpecification>


    <LearningOpportunitySpecification id="LOS2">
    </LearningOpportunitySpecification>

    <LearningOpportunitySpecification id="LOS3">
    </LearningOpportunitySpecification>

    <LearningOpportunityProvider id="LOP1">
        <InstitutionName xml:lang="fi"></InstitutionName>
        <InstitutionName xml:lang="en"></InstitutionName>
        <InstitutionName xml:lang="sv"></InstitutionName>

        <InstitutionAcademicCalendar></InstitutionAcademicCalendar>
        <InstitutionAcademicAuthorities></InstitutionAcademicAuthorities>
        <InstitutionAdmissionProcedures></InstitutionAdmissionProcedures>
        <InstitutionGeneralDescription></InstitutionGeneralDescription>
        <InstitutionalEctsCoordinator></InstitutionalEctsCoordinator>
        <InstitutionMainUniversityRequlations></InstitutionMainUniversityRequlations>

        <GeneralInformationOnCostOfLiving></GeneralInformationOnCostOfLiving>
        <GeneralInformationOnMeals></GeneralInformationOnMeals>
        <GeneralInformationOnMedicalFacilities></GeneralInformationOnMedicalFacilities>
        <GeneralInformationOnFacilitiesForStudentsWithSpecialNeeds></GeneralInformationOnFacilitiesForStudentsWithSpecialNeeds>
        <GeneralInformationOnInsurance></GeneralInformationOnInsurance>
        <GeneralInformationOnFinancialSupport></GeneralInformationOnFinancialSupport>
        <GeneralInformationOnStudentAffairsOffice></GeneralInformationOnStudentAffairsOffice>
        <GeneralInformationOnStudyFacilities></GeneralInformationOnStudyFacilities>
        <GeneralInformationOnInternationalProgrammes></GeneralInformationOnInternationalProgrammes>
        <GeneralInformationForMobileStudents></GeneralInformationForMobileStudents>
        <GeneralInformationOnLanguageCourses></GeneralInformationOnLanguageCourses>
        <GeneralInformationOnInternships></GeneralInformationOnInternships>
        <GeneralInformationOnSportsFacilities></GeneralInformationOnSportsFacilities>
        <GeneralInformationOnExtraMuralAndLeisureFacilities></GeneralInformationOnExtraMuralAndLeisureFacilities>
        <GeneralInformationOnStudentAssociations></GeneralInformationOnStudentAssociations>
    </LearningOpportunityProvider>

</LearningOpportunityData>
